### ISSUE TITLE
Add example of how it works in the editor

### ISSUE THREAD

**Issue by marcgrue** [manolenso/intellij-foundation6#3]

**Comment by manolenso** [comment]
First you should know that I'd used Emmet for several components. 
All snippets are accessing by typing "zf-" follow by two letters for specific a group. Otherwise, for exemple I can see some animated gif's  in [Gitter](https://gitter.im/manolenso/intellij-foundation6)
Of course, First of all before! learn and familiarize  With a very smart "Live Template" system in JetBrains product's.

**Comment by marcgrue** [comment]
Excellent. It would be cool if you could add that animation to the readme. Yes, the live templates in JetBrains editors seem to do more or less the same. Thanks.
